platform :ios, '13.5'

target 'TravelBackInTimeInvestInBitcoinIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TravelBackInTimeInvestInBitcoinIOS
  pod 'timetravelmachine', :path => '../shared-libraries/timetravelmachine'

end
